name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-hack
      run: cargo install cargo-hack
    - name: Build
      run: cargo hack build --feature-powerset --at-least-one-of="vec_storage,stackvec_storage" --verbose
    - name: Run tests
      run: cargo hack test --feature-powerset --at-least-one-of="vec_storage,stackvec_storage" --verbose
