name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-hack
      uses: taiki-e/install-action@cargo-hack
    - name: Build
      run: cargo hack build --feature-powerset --at-least-one-of="vec_storage,stackvec_storage" --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-hack
      uses: taiki-e/install-action@cargo-hack
    - name: Run tests
      run: cargo hack test --feature-powerset --at-least-one-of="vec_storage,stackvec_storage" --verbose

  msrv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-msrv
    - name: Run MSRV check
      run:
      - cargo msrv verify --ignore-lockfile -- cargo test
      - cargo msrv verify --ignore-lockfile -- cargo test --no-default-features --features="stackvec_storage"
