name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-hack
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-hack
        version: '^0.4.7'
    - name: Build
      run: cargo hack build --feature-powerset --at-least-one-of="vec_storage,stackvec_storage" --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-hack
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-hack
        version: '^0.4.7'
    - name: Run tests
      run: cargo hack test --feature-powerset --at-least-one-of="vec_storage,stackvec_storage" --verbose

  msrv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-hack
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-hack
        version: '^0.4.7'
    - name: Install cargo-msrv
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-msrv
        version: '^0.18.4'
    - name: Run MSRV check
      run: cargo msrv verify --ignore-lockfile -- cargo hack test --feature-powerset --at-least-one-of="vec_storage,stackvec_storage"
